-- Migration 015: role-based RLS read policy for behavior_scores (P2 — NOT yet cut over)
--
-- Proven against a staging fixture 2026-05-21. Two access paths:
--   - Teacher: sees only rows they authored (teacher_id = auth.uid()).
--     Teachers do NOT see each other's scores, even on the same student.
--   - Site admin: sees all scores for students at a school they administer.
-- Cross-school isolation verified; cross-teacher boundary verified both ways.
--
-- CUTOVER NOTE: behavior_scores has no school_id, so the site-admin path uses
-- the student_school_id() SECURITY DEFINER helper (migration 017, proven on
-- staging 2026-05-21 — site_admin school-wide visibility resolves with NO grant
-- on students). The policy body below already calls it and is cutover-ready.
--
-- Do NOT apply to prod until: users are migrated to role_assignments AND a full
-- dual-role test passes against real public.behavior_scores on staging. Then
-- uncomment.

-- drop policy if exists scores_role_read on public.behavior_scores;
-- create policy scores_role_read
--   on public.behavior_scores
--   for select
--   using (
--     teacher_id = auth.uid()
--     or public.has_role('site_admin', public.student_school_id(student_id))
--   );

-- (Commented intentionally. Helper exists (017). Uncomment at cutover.)
